#ifndef _A20_AUDIO_H_
#define _A20_AUDIO_H_

#include "CP_Audio.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef enum tagA20_AUDIO_MODE
{
	A20_AUDIO_MODE_LEFT_CODEC_RIGHT_CODEC,
	A20_AUDIO_MODE_LEFT_SPI_RIGHT_SPI,
	A20_AUDIO_MODE_LEFT_MIXED_RIGHT_MIXED,
	A20_AUDIO_MODE_LEFT_CODEC_RIGHT_MIXED,
	A20_AUDIO_MODE_LEFT_SPI_RIGHT_MIXED,
	A20_AUDIO_MODE_LEFT_MIXED_RIGHT_CODEC,
	A20_AUDIO_MODE_LEFT_SPI_RIGHT_CODEC,
	A20_AUDIO_MODE_LEFT_MIXED_RIGHT_SPI,
	A20_AUDIO_MODE_LEFT_CODEC_RIGHT_SPI,
}A20_AUDIO_MODE;

typedef enum tagA20_AUDIO_CMD
{
	A20_AUDIO_CMD_SET_MODE,
	A20_AUDIO_CMD_SET_CODEC_LEFT_VOL,
	A20_AUDIO_CMD_SET_CODEC_RIGHT_VOL,
	A20_AUDIO_CMD_SET_SPI_LEFT_VOL,
	A20_AUDIO_CMD_SET_SPI_RIGHT_VOL,
	A20_AUDIO_CMD_SET_ECHO_VOL,
	A20_AUDIO_CMD_SET_EQ_100HZ_VOL,
	A20_AUDIO_CMD_SET_EQ_1KHZ_VOL,
	A20_AUDIO_CMD_SET_EQ_5KHZ_VOL,
	A20_AUDIO_CMD_TEST_LATENCY,
	A20_AUDIO_CMD_GET_LATENCY,
	A20_AUDIO_CMD_GET_SPI_STATUS,
	A20_AUDIO_CMD_SET_BBE_EN,
	A20_AUDIO_CMD_SET_ECHO_DELAY,
	A20_AUDIO_CMD_SET_BBE_LEVEL,
	A20_AUDIO_CMD_GET_CODEC_LEFT_VPP,
	A20_AUDIO_CMD_GET_CODEC_RIGHT_VPP,
	A20_AUDIO_CMD_GET_SPI_LEFT_VPP,
	A20_AUDIO_CMD_GET_SPI_RIGHT_VPP,
	A20_AUDIO_CMD_SELECT_INPUT,
	A20_AUDIO_CMD_SET_ADC_GAIN,
	A20_AUDIO_CMD_DENOISE_MODE,

	A20_AUDIO_CMD_GET_ECHOVOL,
	A20_AUDIO_CMD_GET_MICVOL,
}A20_AUDIO_CMD;

// ADC SELECT
// 000 LINEINL LINEINR or LINEIN depending on LNRDF
// 001 FMINL FMINR
// 010 MIC1     Default
// 011 MIC2
// 100 MIC1 MIC2
// 101 MIC
// 110 MIXL MIXR
// 111 LINEINL or LINEIN depending on LNRDF MIC1
enum
{
	ADC_LINEIN = 0,
	ADC_FMIN = 1,
	ADC_MIC1 = 2,
	ADC_MIC2 = 3,
	ADC_MIC1_MIC2 = 4,
	ADC_MIC = 5,
	ADC_MIX = 6,
	ADC_LINEINMIC = 7
};


long A20Audio_Set (AUDIO_HANDLE Handle, int Cmd, int Data);
long A20Audio_Get (AUDIO_HANDLE Handle, int Cmd, int *Data);


AUDIO_IN_HANDLE A20AudioIn_Open (AUDIO_HANDLE Handle, AUDIO_PARAM *Param);
long A20AudioIn_Close (AUDIO_IN_HANDLE Handle);
long A20AudioIn_Read (AUDIO_IN_HANDLE Handle, void *BufAddr, unsigned long Size);

AUDIO_OUT_HANDLE A20AudioOut_Open (AUDIO_HANDLE Handle, AUDIO_PARAM *Param);
long A20AudioOut_Close (AUDIO_OUT_HANDLE Handle);
long A20AudioOut_Write (AUDIO_OUT_HANDLE Handle, void *BufAddr, unsigned long Size);

AUDIO_HANDLE A20Audio_Init (int samplerate);
long A20Audio_Finish (AUDIO_HANDLE Handle);


#if defined(__cplusplus)
}
#endif

#endif

